version: '3.8'

services:
  app:
    image: delivery-fee-calculator
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 5173:5173
    container_name: delivery-fee-dev